sudo: required
language: generic
services:
  - docker 

before_install:
  - docker build -t marina/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true marina/docker-react npm run test
